project:
  type: website
  output-dir: docs

website:
  title: "Lesson plan"
  navbar:
    right:
      - icon: github
        href: https://github.com/hezar1000/lesson_plan
        aria-label: Website
      - icon: info-circle
        href: https://www.cs.ubc.ca/~hzarkoob/
        aria-label: Website
    left:
      - href: index.qmd
        text: Home
      # - about.qmd

  open-graph: true
  twitter-card: true
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay

  sidebar:
    # logo: mds-hex-sticker-small.png
    # logo-alt: "MDS Logo Image"
    background: "#3498db"
    style: "docked"
    search: true
    contents:
      - text: "Learning outcomes/Outline"
        href: index.qmd
      - text: "Lecture 1: Basics"
        href: lect1.qmd
      - text: "Lecture 2: Cross-validation"
        href: lect2.qmd
      - text: "References"
        href: ref.qmd


format:
  html:
    theme: cosmo
    css: custom.css
    toc: true

editor:
  render-on-save: true
  markdown:
    wrap: sentence


