project:
  type: website
  output-dir: docs

website:
  title: "Lesson plan"
  navbar:
    right:
      - icon: github
        href: https://github.com/hezar1000/lesson_plan
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  open-graph: true
  twitter-card: true
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay

  sidebar:
    # logo: mds-hex-sticker-small.png
    # logo-alt: "MDS Logo Image"
    background: "#3498db"
    style: "docked"
    search: true
    contents:
      - text: "Learning outcomes"
        href: index.qmd
      - text: "Lecture 1: Intro"
        href: index.qmd
      - text: "Lecture 2: Cross Validation"
        href: index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



